markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : gT0 Bl0g
production_url : http://tommasinigiovanni.github.io
description: "projects and other things by Giovanni Tommasini."
disqus_shortname: giovanni_tommasini
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author : Giovanni Tommasini
  name : Giovanni Tommasini
  github : tommasinigiovanni
  twitter : giovi_tom
  email: tommasini.giovanni@gmail.com
baseurl: /up