#
###################################
# Site wide configuration
####################################
#
title: tommasinigiovanni.github.io
email: tommasini.giovanni@gmail.com
description: A simple and awesome blog theme powered by jekyll
url: http://tommasinigiovanni.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Rome
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: gT0
  avatar: leonids-logo.png
  job: "Computer science enthusiast."
  bio: #""
  email: tommasini.giovanni@gmail.com
  disqus-shortname:
  twitter: giovi_tom
  facebook: giovanni.tommasini
  google:
    plus: +GiovanniTommasini
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: tommasinigiovanni
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: giovannitommasini
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
